variables:
  PROJECT_NAMESPACE: mcb
  POD_NUM: 1
  DEPLOYMENT_FILE: "deployment.yaml"

stages:
  - build
  - push
  - test
  - deploy

build:
  stage: build
  only:
    - dev
    - test 
    - master
  image: java:8-jdk
  variables:
    GRADLE_HOME: ".gradle/"
    GRADLE_PROJECT_HOME: ".gradle/current/"
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ${GRADLE_HOME}
      - ${GRADLE_PROJECT_HOME}
  script:
    - ./gradlew --no-daemon -g ${GRADLE_HOME} --project-cache-dir ${GRADLE_PROJECT_HOME}
      -PzdxPullUser=$MAVEN_PULL_USER -PzdxPullPassword=$MAVEN_PULL_PASSWORD
      -PzdxPushUser=$MAVEN_PUSH_USER -PzdxPushPassword=$MAVEN_PUSH_PASSWORD
      build
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - http/build/libs
    expire_in: 3 month

build-docker:
  stage: push
  image: 
    name: registry.sre.shusj.com/open-images/kaniko:master
    entrypoint: [""]
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /root/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  only:
    - dev
    - test 
    - master

deploy-job:
  stage: deploy
  image:
    name: bitnami/kubectl:1.14.3-ol-7-r114
  script:
    - mkdir -p /tmp/.kube
    - KUBE_CONFIG=`echo ${CI_COMMIT_REF_NAME} | tr '[:lower:]' '[:upper:]'` &&
      KUBE_CONFIG=KUBE_CONFIG_${KUBE_CONFIG} &&
      KUBE_CONFIG=`eval echo '$'"${KUBE_CONFIG}"` &&
      echo -n ${KUBE_CONFIG} | base64 -d > /tmp/.kube/config
    - sed -i "s#REPLICA#${POD_NUM}#" ${DEPLOYMENT_FILE} &&
      sed -i "s#APP_NAME#${PROJECT_NAMESPACE}-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}#g" ${DEPLOYMENT_FILE} &&
      sed -i "s#MY_PROJECT#${PROJECT_NAMESPACE}#g" ${DEPLOYMENT_FILE} &&
      sed -i "s#IMAGE_SHA#$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA#" ${DEPLOYMENT_FILE} &&
      sed -i "s#MY_APPNAME#${CI_PROJECT_NAME}#g" ${DEPLOYMENT_FILE} &&
      sed -i "s#MY_NAMESPACE#${CI_COMMIT_REF_NAME}#g" ${DEPLOYMENT_FILE}
    - mv config/spring-config-${CI_COMMIT_REF_NAME}.yml config/spring-config.yml
    - kubectl delete cm ${PROJECT_NAMESPACE}-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME} --ignore-not-found -n ${CI_COMMIT_REF_NAME}-chain --kubeconfig=/tmp/.kube/config &&
      sleep 1 &&
      kubectl create cm ${PROJECT_NAMESPACE}-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME} --from-file=config/spring-config.yml -n ${CI_COMMIT_REF_NAME}-chain --kubeconfig=/tmp/.kube/config
    - kubectl apply -f deployment.yaml -n ${CI_COMMIT_REF_NAME}-chain --kubeconfig=/tmp/.kube/config
  only:
    - dev
    - test
    - master
